OrdererOrgs:
  - Name: Orderer
    Domain: votechain.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.votechain.com
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Org2
    Domain: org2.votechain.com
    Template:
      Count: 1
    Users:
      Count: 1